### PR TITLE
Test.only fix

### PR DESCRIPTION
**Pull request by goodmind**
TODO: 
- [x] Tests

**Done!**

### CODE REVIEW

**Comment by Flet** [comment]
Cool, just let me know when to review! :)

**Comment by goodmind** [comment]
@Flet you can review now :) Maybe we can split travis tests with env matrix

**Comment by Flet** [comment]
This is great, thanks! I added a little more to the `only` test to cover separate files. 👍

**Comment by Flet** [comment]
Published as `tape-nock@1.3.0`

**Comment by goodmind** [comment]
It seems that you published `master` branch not `next`?

**Pull request merged**
